- name: Install Nginx and PHP-FPM
  hosts: dev-server
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
   #- common
   # - nginx
   # - php-fpm
   # - vhost
   # - percona
     - docker
