---
- name: Copy Nginx Pagespeed for compile
  raw : wget http://ho.acomindo.com:9091/nginx-1.11.5.tar.gz

- name: Install Depedencies Package
  raw : yum -y install gcc-c++ pcre-devel pcre-devel zlib-devel make unzip openssl-devel

- name: Package for GCC Compile pagespeed
  raw : rpm --import https://linux.web.cern.ch/linux/scientific6/docs/repository/cern/slc6X/i386/RPM-GPG-KEY-cern

- name: Package for GCC Compile pagespeed
  raw : wget -O /etc/yum.repos.d/slc6-devtoolset.repo https://linux.web.cern.ch/linux/scientific6/docs/repository/cern/devtoolset/slc6-devtoolset.repo

- name: Package for GCC Compile pagespeed
  raw : yum -y install devtoolset-2-gcc-c++ devtoolset-2-binutils

- name: Add this before run compile nginx
  raw : PS_NGX_EXTRA_FLAGS="--with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc"
 
- name: extract nginx pagespeed
  raw : tar zxvf nginx-1.11.5.tar.gz

- name: add compile.sh
  template: src=compile.sh dest=~/compile.sh 

- name: compile pagespeed 
  raw : chmod +x compile.sh && ./compile.sh
