---
- name: Copy Nginx Pagespeed for compile
  raw : wget http://ho.acomindo.com:9091/nginx-1.11.5.tar.gz /tmp/

- name: Install Depedencies Package
  raw : yum -y install gcc-c++ pcre-devel zlib-devel make

- name: Package for GCC Compile pagespeed
  raw : wget https://linux.web.cern.ch/linux/scientific6/docs/repository/cern/slc6X/i386/RPM-GPG-KEY-cern

- name: Package for GCC Compile pagespeed
  raw : rpm --import RPM-GPG-KEY-cern

- name: Package for GCC Compile pagespeed
  raw : wget -O /etc/yum.repos.d/slc5-devtoolset.repo https://linux.web.cern.ch/linux/scientific5/docs/repository/cern/devtoolset/slc5-devtoolset.repo

- name: Package for GCC Compile pagespeed
  raw : yum -y install devtoolset-2-gcc-c++ devtoolset-2-binutils

- name: Add this before run compile nginx
  raw : PS_NGX_EXTRA_FLAGS="--with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc"
 
- name: extract nginx pagespeed
  raw : cd /tmp/ && tar zxvf nginx-1.11.5.tar.gz

- name: compile pagespeed 
  raw : cd /tmp/nginx-1.11.5/ && ./configure --add-dynamic-module=ngx_pagespeed-release-1.11.33.4-beta ${PS_NGX_EXTRA_FLAGS} --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'

- name: make && make install
  raw : cd /tmp/nginx-1.11.5/ && make && make install
