---
- name: Install nginx
  yum: name=nginx state=latest

- name: Create folder sites-available
  raw : mkdir -p /etc/nginx/sites-available

- name: Create folder sites-available
  raw : mkdir -p /etc/nginx/sites-enabled

- name: Copy nginx default config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: copy vhostset(setup vhost)
  template: src=vhostset dest=/usr/sbin/vhostset

- name: chmod +x vhostset
  raw : chmod +x /usr/sbin/vhostset
