---
- name: download percona repo
  raw : yum -y install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm

- name : install percona mysql server
  raw  : yum -y install Percona-Server-server-56 

- name : Copy Default my.cnf
  template: src=my.cnf dest=/etc/my.cnf
  notify: restart mysql
