---
- name: Copy Nginx repository definition
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: download import key
  get_url: url=http://nginx.org/keys/nginx_signing.key dest=/tmp/nginx_signing.key

- name: import key
  rpm_key: state=present key=/tmp/nginx_signing.key

- name: Install nginx
  yum: name=nginx state=latest

- name: Create folder sites-available
  raw : mkdir -p /etc/nginx/sites-available

- name: Create folder sites-available
  raw : mkdir -p /etc/nginx/sites-enabled

- name: Copy nginx default config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: copy vhostset(setup vhost)
  template: src=vhostset dest=/usr/sbin/vhostset

- name: chmod +x vhostset
  raw : chmod +x /usr/sbin/vhostset
